### ISSUE TITLE
Q

### ISSUE THREAD

**Issue by ghost** [herlesupreeth/Open5gs_Config#7]
q

**Comment by herlesupreeth** [comment]
there is something wrong in your configs, pgw i assume because PGW is rejecting pcrf with FQDN pcrf.localdomain since your have configured PCRF with FQDN pcrf.epc.mnc001.mcc001.3gppnetwork.org

![image](https://user-images.githubusercontent.com/4115839/103230286-58646180-4935-11eb-8465-ae470dc42237.png)

**Comment by ghost** [comment]
Yea, Sorry its Solved

Thanks
